---
title: "Detect Cancer Cells"
author: "Chongxuan Bi"
date: "1/1/2021"
output: pdf_document
---

# Import data
library(readr)
data = read_csv("training.csv")
test = read_csv("test.csv")
data = data[,-1]
test = test[,-1]


# Import libraries
library(MASS) 
library(caret)
library(MLeval)
library(nnet)
library(glmnet)
library(readr)

# Convert class to factors:0 is ng, 1 is og, 2 is tsg
data$class = as.factor(data$class)
levels(data$class) = c('ng', 'og', 'tsg')

# Train/validation data split
set.seed(1)
train_index = createDataPartition(data$class, p = 0.7, list = F)
train = data[train_index,]
valid = data[-train_index,]

# Feature Selection
# Remove Collinear Variables for the training data
correlation_matrix = cor(train[,-98])
hc = findCorrelation(correlation_matrix,cutoff = 0.7)
hc = sort(hc)
reduced_train = train[,-c(hc)]

# Trial 1: Fit KNN model (caret) with threshold 0.5
train_control <- trainControl(method="cv", number = 5, classProbs = TRUE, 
savePredictions = TRUE)
knnfit = train(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing, data = train, method = 'knn', preProc = c('center', 'scale'), 
trControl = train_control, tuneGrid = expand.grid(k = seq(1, 100, 5)))

knn_pred = predict(knnfit, valid, type = 'prob')
knn_pred_no_prob = predict(knnfit, valid)
confusionMatrix(knn_pred_no_prob, valid$class)

# Manually adjust threshold
knn_pred_manual = ifelse(knn_pred_prob$ng == 1, 'ng',
ifelse(knn_pred_prob$og > 0.6 | knn_pred_prob$tsg == 0, 'og', 'tsg'))
knn_pred_manual = as.factor(knn_pred_manual)
levels(knn_pred_manual) = c('ng', 'og', 'tsg')
confusionMatrix(knn_pred_manual, valid$class)

# Trial 2: Fit LDA Model (caret) with manually adjusted threshold

ldafit = lda(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing,data = train)
ldafit_pred = predict(ldafit, valid)
ldafit_pred_prob = predict(ldafit, valid, type = 'prob')
ldafit_pred_manual = rep(NA, 953)
ldafit_pred_manual = ifelse(ldafit_pred_prob$posterior[,1] >= 0.9, 0, as.numeric(apply(ldafit_pred_prob$posterior[,2:3], 1, which.max)))
table(ldafit_pred_manual, valid$class)

# Trial 3: Fit Basic LR models with manually adjusted threshold

lrfit = multinom(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing,data = train)
lrfit_pred_prob = predict(lrfit, valid, type = 'prob')
lrfit_pred_manual = rep(NA, 953)
lrfit_pred_manual = ifelse(s_lrfit_pred_prob[,1] >= 0.94, 0,
as.numeric(apply(s_lrfit_pred_prob [,2:3], 1, which.max)))
print(table(lrfit_pred_manual, valid$class))



# Trial 4: Fit LR models with interaction terms & manually adjusted threshold

lrfit = multinom(class ~                                           
                   BioGRID_betweenness+Silent_KB_Ratio+
                   Silent_fraction+
                   Missense_Entropy*N_Splice*Splice_TO_Total_Ratio+MGAentropy+
                   GDI*Missense_Damaging_TO_Benign_Ratio+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   Cell_proliferation_rate_CRISPR_KD+
                   VEST_score+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   Super_Enhancer_percentage+intolerant_pLI+
                   Synonymous_Zscore+
                   ncGERP+
                   S50_score_replication_timing*One_Minus_S50_score_replication_timing+
                   BioGRID_log_degree+
                   H4K20me1_height+
                   Broad_H3K79me2_percentage+
                   Broad_H3K36me3_percentage*
                   Broad_H3K4me1_percentage*H3K4me1_height+
                   Broad_H3K27ac_percentage+
                   Broad_H3K27me3_percentage*H3K27me3_width+
                   H3K4me3_height+
                   LOF_TO_Benign_Ratio, data = train)
lrfit_pred = predict(lrfit, valid)
lrfit_pred_prob = predict(lrfit, valid, type = 'prob')
lrfit_pred_manual = rep(NA, 953)
lrfit_pred_manual = ifelse(lrfit_pred_prob[,1] >= 0.94, 
0, as.numeric(apply(lrfit_pred_prob[,2:3], 1, which.max)))
table(lrfit_pred_manual, valid$class)

# Additional Trial: Fit LR models with manually adjusted threshold accompanied by KNN method

levels(knn_pred) = c(0,1,2)
knn_pred = as.numeric(knn_pred) - 1
lrfit_pred_manual = rep(NA, 952)
  for(i in 1:nrow(valid)){
    if(lrfit_pred_prob[i,1] >= t){
      lrfit_pred_manual[i] = 0
    } else if (lrfit_pred_prob[i,1]>= 0.90 && lrfit_pred_prob[i,1] < t){
      if(abs(lrfit_pred_prob[i,2]-lrfit_pred_prob[i,3]) <= 0.05){
        lrfit_pred_manual[i] = 0
      } else {
        lrfit_pred_manual[i] = as.numeric(which.max(lrfit_pred_prob [i,2:3]))
        if(as.numeric(which.max(lrfit_pred_prob [i,2:3]))!= as.numeric(which.max(ldafit_pred[i,2:3]))){
          diff_lr = abs(lrfit_pred_prob [i,2]-lrfit_pred_prob [i,3])
          diff_lda = abs(ldafit_pred[i,2]-ldafit_pred[i,3])
          lrfit_pred_manual[i] = ifelse(diff_lr>diff_lda,as.numeric(which.max(lrfit_pred_prob [i,2:3])),as.numeric(which.max(ldafit_pred[i,2:3])))
        }
      }
    } else if (lrfit_pred_prob[i,1]>= 0.70 && lrfit_pred_prob[i,1] < 0.90 ){
      if(abs(lrfit_pred_prob[i,2]-lrfit_pred_prob[i,3]) > 0.05){
        lrfit_pred_manual[i] = as.numeric(which.max(lrfit_pred_prob [i,2:3]))
      } else {
        lrfit_pred_manual[i] = 0
      }
    } else if (lrfit_pred_prob[i,1] < 0.7) {
      if(abs(lrfit_pred_prob[i,2]-lrfit_pred_prob[i,3]) > 0.05){
        lrfit_pred_manual[i] = as.numeric(which.max(lrfit_pred_prob [i,2:3]))
      } else {
        lrfit_pred_manual[i] = as.numeric(knn_pred[i])
      }
    }
  }       
  print(table(lrfit_pred_manual, valid$class))

# Final Model: Fit LR models with scaling prediction probabilities & manually adjust threshold

lrfit = multinom(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing,data = train)

lrfit_pred_prob = predict(lrfit, valid, type = 'prob')
s_lrfit_pred_prob = scale(abs(log(lrfit_pred_prob)),center = F)
lrfit_pred_manual = rep(NA, 953)
threshold = 0.08 
lrfit_pred_manual = ifelse(s_lrfit_pred_prob[,1] <= threshold, 
0, as.numeric(apply(s_lrfit_pred_prob [,2:3], 1, which.min)))
print(table(lrfit_pred_manual, valid$class))
  
# Cross Validation

LRfit_all <- train(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing,
data = train, method = "multinom", 
preProc = c("center", "scale"), trControl = train_control)

lrfit_cv_pred = predict(LRfit_cv, valid, type = 'prob')
s_lrfit_cv_pred = scale(abs(log(lrfit_cv_pred)))
lrfit_cv_pred_manual = rep(NA, 953)
threshold = 0.08
lrfit_pred_manual = 
ifelse(s_lrfit_cv_pred[,1] <= x, 0, as.numeric(apply(s_lrfit_cv_pred [,2:3], 1, which.min)))
print(table(lrfit_cv_pred_manual, valid$class))

#Ourlier Removal
p<-"class ~Silent_KB_Ratio+N_Splice+Missense_Entropy+Splice_TO_Total_Ratio+Silent_fraction
                 +Recurrent_missense_fraction+Inactivating_mutations_fraction+MGAentropy+VEST_score
                 +Cell_proliferation_rate_CRISPR_KD+Super_Enhancer_percentage+BioGRID_log_degree
                 +Gene_body_hypermethylation_in_cancer+Canyon_genebody_hypermethylation+intolerant_pLI
                 +Synonymous_Zscore+GDI+ncGERP+Broad_H3K9me3_percentage+Broad_H3K9ac_percentage
                 +Broad_H3K9me2_percentage+H4K20me1_height
                 +S50_score_replication_timing"
library(stringr)
m<-str_extract_all(p, "\\w+")
f<-m[[1]]
outllier_finder<-data.frame(data[,f])

for( i in 2: dim(outllier_finder)[2]){
current<-outllier_finder[,i]
lower_bound <- quantile(current, 0.025)
upper_bound <- quantile(current, 0.975)
outlier_ind <- which(current < lower_bound | current > upper_bound)

me<-median(current[-outlier_ind])
print(me)
for(j in 1:length(outlier_ind)){
   outllier_finder[outlier_ind[j],i]<-me
  }
}

set.seed(1)
train_index = createDataPartition(data$class, p = 0.7, list = F)
train_outlier = outllier_finder[train_index,]
valid_outlier = outllier_finder[-train_index,]

# Fit to whole data and predict on test

lrfit_test = multinom(class ~
                   Silent_KB_Ratio+
                   N_Splice+
                   Missense_Entropy+
                   Splice_TO_Total_Ratio+
                   Silent_fraction+
                   Recurrent_missense_fraction+
                   Inactivating_mutations_fraction+
                   MGAentropy+VEST_score+
                   Cell_proliferation_rate_CRISPR_KD+
                   Super_Enhancer_percentage+
                   BioGRID_log_degree+
                   Gene_body_hypermethylation_in_cancer+
                   Canyon_genebody_hypermethylation+
                   intolerant_pLI+
                   Synonymous_Zscore+
                   GDI+ncGERP+
                   Broad_H3K9me3_percentage+
                   Broad_H3K9ac_percentage+
                   Broad_H3K9me2_percentage+
                   H4K20me1_height+
                   S50_score_replication_timing,data = data)

lrfit_pred_prob_test = predict(lrfit_test, test, type = 'prob')
s_lrfit_pred_prob_test = scale(abs(log(lrfit_pred_prob_test)),center = F)
lrfit_pred_manual_test = rep(NA, 953)
threshold = 0.08 
lrfit_pred_manual_test = ifelse(s_lrfit_pred_prob_test[,1] <= threshold, 
0, as.numeric(apply(s_lrfit_pred_prob_test [,2:3], 1, which.min)))
print(table(lrfit_pred_manual_test, valid$class))


# Generate CSV file
result= data.frame("id" = c(3178:4540), "class"= as.numeric(lrfit_pred_manual_test),
row.names = NULL)

result_csv = write.csv(result, file = "result_test.csv",row.names = FALSE)